In [2]:
import numpy as np
import pandas as pd

In [3]:
list = [1,2,5,4]

In [4]:
lista =  np.array(list)#casting a list into an array

In [5]:
list

[1, 2, 5, 4]

In [6]:
np.arange(0,10,2)#range from  0 to 10 with 2 space betweeen
#start stop step

array([0, 2, 4, 6, 8])

In [7]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [8]:


np.ones((5,2))# used to create tables for ones and zeros

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
np.eye(4) #for creating an identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.random.rand(5)

array([0.65664709, 0.75940313, 0.36051665, 0.54720181, 0.1383557 ])

In [11]:
np.random.randn(4,4)

array([[ 1.58817979, -1.41532447,  0.37544769,  0.97218312],
       [-0.21215746, -0.46541226,  0.2987324 ,  0.26926151],
       [-0.40680471, -0.24033055,  1.59539801,  0.69211245],
       [ 0.35727227,  0.19492155,  2.28458387, -0.08641438]])

In [12]:
np.random.randint(1,100,10)

array([10, 13, 85,  9, 61, 54,  1, 80, 81, 18])

In [13]:
list = ['a', 'b', 'c', 'd']
data = [10,20,30,40]
my_data = np.array(data)
final_data = {'a':10,'b':20,'c':30,'d':40}

In [14]:
pd.Series(data = data)

0    10
1    20
2    30
3    40
dtype: int64

In [15]:
pd.Series(data = data, index = list)

a    10
b    20
c    30
d    40
dtype: int64

In [16]:
 pd. Series(my_data)

0    10
1    20
2    30
3    40
dtype: int32

In [17]:
pd.Series(final_data)

a    10
b    20
c    30
d    40
dtype: int64

In [18]:
from numpy.random import randn

In [19]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [20]:
df

W         X         Y         Z
A  1.170785  1.185102  0.947971 -1.166892
B -0.126455  1.375730  1.840229 -0.937745
C -0.598650  1.834926 -1.794283  0.410043
D  3.501036  1.207071 -0.924176 -0.411062
E -1.636375 -0.696430  0.085064  0.544596

In [21]:
df['W']

A    1.170785
B   -0.126455
C   -0.598650
D    3.501036
E   -1.636375
Name: W, dtype: float64

In [22]:
type(df)

pandas.core.frame.DataFrame

In [23]:
df.Y

A    0.947971
B    1.840229
C   -1.794283
D   -0.924176
E    0.085064
Name: Y, dtype: float64

In [24]:
df[['W','Y']]

W         Y
A  1.170785  0.947971
B -0.126455  1.840229
C -0.598650 -1.794283
D  3.501036 -0.924176
E -1.636375  0.085064

In [25]:
df['new']= df['X'] + df['Y']

In [26]:
df

W         X         Y         Z       new
A  1.170785  1.185102  0.947971 -1.166892  2.133073
B -0.126455  1.375730  1.840229 -0.937745  3.215958
C -0.598650  1.834926 -1.794283  0.410043  0.040643
D  3.501036  1.207071 -0.924176 -0.411062  0.282895
E -1.636375 -0.696430  0.085064  0.544596 -0.611366

In [27]:
df.loc['B']

W     -0.126455
X      1.375730
Y      1.840229
Z     -0.937745
new    3.215958
Name: B, dtype: float64

In [28]:
df > 0

W      X      Y      Z    new
A   True   True   True  False   True
B  False   True   True  False   True
C  False   True  False   True   True
D   True   True  False  False   True
E  False  False   True   True  False

In [29]:
booldf = df > 0

In [30]:
df[booldf]

W         X         Y         Z       new
A  1.170785  1.185102  0.947971       NaN  2.133073
B       NaN  1.375730  1.840229       NaN  3.215958
C       NaN  1.834926       NaN  0.410043  0.040643
D  3.501036  1.207071       NaN       NaN  0.282895
E       NaN       NaN  0.085064  0.544596       NaN

In [31]:
df [df > 0]

W         X         Y         Z       new
A  1.170785  1.185102  0.947971       NaN  2.133073
B       NaN  1.375730  1.840229       NaN  3.215958
C       NaN  1.834926       NaN  0.410043  0.040643
D  3.501036  1.207071       NaN       NaN  0.282895
E       NaN       NaN  0.085064  0.544596       NaN

In [32]:
df['Y'] >0

A     True
B     True
C    False
D    False
E     True
Name: Y, dtype: bool

In [33]:
df[df['Y'] > 0]

W         X         Y         Z       new
A  1.170785  1.185102  0.947971 -1.166892  2.133073
B -0.126455  1.375730  1.840229 -0.937745  3.215958
E -1.636375 -0.696430  0.085064  0.544596 -0.611366

In [34]:
df

W         X         Y         Z       new
A  1.170785  1.185102  0.947971 -1.166892  2.133073
B -0.126455  1.375730  1.840229 -0.937745  3.215958
C -0.598650  1.834926 -1.794283  0.410043  0.040643
D  3.501036  1.207071 -0.924176 -0.411062  0.282895
E -1.636375 -0.696430  0.085064  0.544596 -0.611366

In [35]:
df[df['X'] < 0]

W        X         Y         Z       new
E -1.636375 -0.69643  0.085064  0.544596 -0.611366

In [36]:
df[df['W']>0][['Y','X']]

Y         X
A  0.947971  1.185102
D -0.924176  1.207071

In [37]:
df [(df['W']>0)|(df['X']>0)]

W         X         Y         Z       new
A  1.170785  1.185102  0.947971 -1.166892  2.133073
B -0.126455  1.375730  1.840229 -0.937745  3.215958
C -0.598650  1.834926 -1.794283  0.410043  0.040643
D  3.501036  1.207071 -0.924176 -0.411062  0.282895

In [38]:
d = {'A':[1,2,np.nan], 'B':[5,np.nan,np.nan], 'C':[6,5,3]}

In [48]:
df =pd.DataFrame(d)

In [49]:
df

A    B  C
0  1.0  5.0  6
1  2.0  NaN  5
2  NaN  NaN  3

In [50]:
df.dropna()

A    B  C
0  1.0  5.0  6

In [51]:
df.dropna(axis =1)

C
0  6
1  5
2  3

In [52]:
df.dropna(thresh = 2)

A    B  C
0  1.0  5.0  6
1  2.0  NaN  5

In [53]:
df.fillna(value ='NULL')

A     B  C
0     1     5  6
1     2  NULL  5
2  NULL  NULL  3

In [54]:
df['A'].fillna(value= (df['A'].mean()))

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [55]:
data = {'Sict':['IMT','CPT','CSS','LIT','IMT','CSS'],
       'Students':['Tom','James','Tina','Toma','Tonia','Mggie'],
       'Scores':[200,650,782,546,900,265]}

In [56]:
df =pd.DataFrame(data)
df

Sict Students  Scores
0  IMT      Tom     200
1  CPT    James     650
2  CSS     Tina     782
3  LIT     Toma     546
4  IMT    Tonia     900
5  CSS    Mggie     265

In [57]:
bysco=df.groupby('Sict')

In [58]:
bysco.mean()

Scores
Sict        
CPT    650.0
CSS    523.5
IMT    550.0
LIT    546.0

In [59]:
bysco.sum()

Scores
Sict        
CPT      650
CSS     1047
IMT     1100
LIT      546

In [60]:
bysco.std()

Scores
Sict            
CPT          NaN
CSS   365.574206
IMT   494.974747
LIT          NaN

In [61]:
bysco.sum().loc['CSS']

Scores    1047
Name: CSS, dtype: int64

In [62]:
bysco.count()

Students  Scores
Sict                  
CPT          1       1
CSS          2       2
IMT          2       2
LIT          1       1

In [63]:
bysco.describe()

Scores                                                        
      count   mean         std    min     25%    50%     75%    max
Sict                                                               
CPT     1.0  650.0         NaN  650.0  650.00  650.0  650.00  650.0
CSS     2.0  523.5  365.574206  265.0  394.25  523.5  652.75  782.0
IMT     2.0  550.0  494.974747  200.0  375.00  550.0  725.00  900.0
LIT     1.0  546.0         NaN  546.0  546.00  546.0  546.00  546.0

In [65]:
bysco.describe().ipynb_checkpoints/transpose()['IMT']

Scores  count      2.000000
        mean     550.000000
        std      494.974747
        min      200.000000
        25%      375.000000
        50%      550.000000
        75%      725.000000
        max      900.000000
Name: IMT, dtype: float64

NameError: name 'np' is not defined